version : "3.7"

networks:
  lemp_stack_claimswiki:

services:
    web_app:
       build: .
       volumes:
         - ./src:/var/www/html
       ports:
         - 80:80
    db:
       image: mariadb:10.5.9
       restart: always
       volumes:
          - ./db_data:/var/lib/mysql
          - ./configs/my.cnf:/etc/mysql/conf.d/my.cnf
       environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: 'dockerdb'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: 'root'
       ports:
         - '3306:3306'
       healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
        interval: '5s'
        retries: 5  
    
    admin: 
       image: phpmyadmin
       container_name: phpmyadmin
       environment:
         PMA_HOST: 'db'
         MYSQL_USERNAME: 'root'
         MYSQL_ROOT_PASSWORD: 'root'
       depends_on:
          db:
            condition:
              service_healthy      
       ports: 
         - '8080:80'
       networks:
         - lemp_stack_claimswiki
    